### ISSUE TITLE
Installation/compilation instructions

### ISSUE THREAD

**Issue by proycon** [ErwinKomen/FoliaEntity#1]
Hi Erwin,

Could you perhaps provide a short README with compilation/installation instructions for Mono (on Linux)? (without Visual Studio Code, I need it to be scriptable). I don't know much about C# and am trying to get this integrated into the new Nederlab pipeline.

Thanks!

**Comment by ErwinKomen** [comment]
There's some documentation available on https://github.com/ErwinKomen/FoliaEntity/wiki (in Dutch).
Section 2.1 is on FoliaEntity.

**Comment by ErwinKomen** [comment]
I have added a link to the wiki on the home page of FoliaEntity
