### ISSUE TITLE
Configurable endpoints

### ISSUE THREAD

**Issue by proycon** [ErwinKomen/FoliaEntity#2]
I'm planning on running the spotlight service locally, which just involves a change in address afaik. Could you make it configurable? Perhaps for the others too? If I could disable certain services in case some turn out to be too slow (I understand you implemented multiple?) then that would be welcome too.

**Comment by ErwinKomen** [comment]
See the renewed documentation (Wiki page). The `-u` option has been added that allows specifying a different URI for each of the four web services that can be used.
