### ISSUE TITLE
Declaration of alignment-annotation is in wrong XML namespace

### ISSUE THREAD

**Issue by proycon** [ErwinKomen/FoliaEntity#6]
Hi Erwin,

A problem popped up when trying to validate the resulting FoLiA documents, should be ease to correct though. Your declaration of ``<alignment-annotation>`` does not use the FoLiA XML namespace, it outputs as follows and explicitly resets the namespace:

```xml
<alignment-annotation annotator="" annotatortype="auto" set="ErwinKomen-NEL" xmlns="" />
```

This causes the document not to validate. You'll probably need to pass the FoLiA namespace somewhere around https://github.com/ErwinKomen/FoliaEntity/blob/master/FoliaEntity/feConv.cs#L258 . I don't know the API so you can probably find it quicker than I can.

**Comment by ErwinKomen** [comment]
Hi Maarten,

Thanks for your explanation, which really helps me to see what is going on where and why.
The solution was in what used to be line 258, but now is lines 262-267. The `<alignment-annotation>` child created under `ndxFoliaS` must explicitly receive the `xmlns` attribute of FoLiA, and only then will the writer in line 268 realize that this child is under the same namespace.

Please let me know if it works now after the correction.

**Comment by proycon** [comment]
Perfect! Works now, thanks!
